openapi: 3.0.0
info:
  title: CovidAPI.site
  version: '1.0'
  description: 'COVID-19 Data API for up-to-date statistics for an address with country, state, and local confirmed cases and deaths information.'
  contact:
    name: CovidAPI.site
    url: 'https://covidapi.site'
    email: support@covidapi.site
servers:
  - url: 'https://api.covidAPI.site/v1'
paths:
  /data:
    parameters: []
    get:
      summary: Covid19 Stats for an Address
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/COVID-data'
              examples:
                example-1:
                  value:
                    address: '503 W 139th St, New York, NY 10031, USA'
                    date: '2020-05-17'
                    last_update: '2020-05-17T06:05:58Z'
                    iso: USA
                    country:
                      country: United States of America
                      country_code: US
                      confirmed: 1467820
                      deaths: 88754
                      confirmed_diff: 24996
                      deaths_diff: 1224
                    state:
                      state: New York
                      confirmed: 348232
                      deaths: 28049
                      confirmed_diff: 2419
                      deaths_diff: 171
                    county:
                      county: New York City
                      confirmed: 191600
                      deaths: 20576
                      confirmed_diff: 1243
                      deaths_diff: 100
            application/xml:
              schema:
                type: object
                properties: {}
            multipart/form-data:
              schema:
                type: object
                properties: {}
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error-data'
        '429':
          description: Too Many Requests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error-data'
      operationId: get-v1-data?address=address
      description: "Up-to-date COVID19 statistics\_with information at the Country-level globally, and State-Level and\_County-Level data for addresses in the USA."
      parameters:
        - schema:
            type: string
          in: query
          name: address
          description: 'A global address, location or place name'
          required: true
components:
  schemas:
    COVID-data:
      title: COVID-Data
      type: object
      x-examples:
        Example (New York City Fire Department):
          address: '42 South St, New York, NY 10005, USA'
          date: '2020-05-17'
          last_update: '2020-05-17T02:28:48Z'
          iso: USA
          country:
            country: United States of America
            country_code: US
            confirmed: 1442824
            deaths: 87530
            confirmed_diff: 25050
            deaths_diff: 1632
          state:
            state: New York
            confirmed: 345813
            deaths: 27878
            confirmed_diff: 2762
            deaths_diff: 237
          county:
            county: New York City
            confirmed: 190357
            deaths: 20476
            confirmed_diff: 1812
            deaths_diff: 70
        Example (Eiffel Tower):
          address: 'Champ de Mars, 5 Avenue Anatole France, 75007 Paris, France'
          date: '2020-05-17'
          last_update: '2020-05-17T03:29:23Z'
          iso: FRA
          country:
            country: France
            country_code: FR
            confirmed: 179630
            deaths: 27532
            confirmed_diff: 636
            deaths_diff: 104
      description: COVID-Data Successful Response Schema
      x-tags:
        - REST
        - API
        - COVID
      properties:
        address:
          type: string
          description: Formatted global address
        date:
          type: string
          description: Date for the statistics provided
        last_updated:
          type: string
          description: Last updated date and time for the information
        iso:
          type: string
          description: ISO 3166-1 alpha-3 country code
        country:
          type: object
          description: Country-level statistics
          properties:
            country:
              type: string
              description: Country name
            countrycode:
              type: string
              description: ISO 3166-1 alpha-2 country code
            confirmed:
              type: string
              description: 'Total number of confirmed cases as of "last_updated"'
            deaths:
              type: string
              description: 'Total number of deaths as of "last_updated"'
            confirmed_diff:
              type: string
              description: 'Difference in the total number of confirmed cases between yesterday and today based on "date"'
            deaths_diff:
              type: string
              description: 'Difference in the total number of deaths between yesterday and today based on "date"'
        state:
          type: object
          description: State-level statistics
          properties:
            state:
              type: string
              description: State name
            confirmed:
              type: string
              description: 'Total number of confirmed cases as of "last_updated"'
            deaths:
              type: string
              description: 'Total number of deaths as of "last_updated"'
            confirmed_diff:
              type: string
              description: 'Difference in the total number of confirmed cases between yesterday and today based on "date"'
            deaths_diff:
              type: string
              description: 'Difference in the total number of deaths between yesterday and today based on "date"'
        county:
          type: object
          description: County-level statistics
          properties:
            county:
              type: string
              description: County name
            confirmed:
              type: string
              description: 'Total number of confirmed cases as of "last_updated"'
            deaths:
              type: string
              description: 'Total number of deaths as of "last_updated"'
            confirmed_diff:
              type: string
              description: 'Difference in the total number of confirmed cases between yesterday and today based on "date"'
            death_diff:
              type: string
              description: 'Difference in the total number of deaths between yesterday and today based on "date"'
    Error-data:
      title: Error-data
      type: object
      description: COVID-Data Error Response Schema
      properties:
        statusCode:
          type: number
          description: HTTP Status Code Returned
        statusMessage:
          type: string
          description: Status code message
        message:
          type: string
          description: Descriptive error message
  securitySchemes: {}
